Repository devs-plan/Ketchup_front-end, pull requests merged in 2024-05, with the labels that each got.

#2 [Feature-0503](#1) - main, 컴포넌트 추가 및 수정
  package-lock.json
  package.json
  public/index.html
  src/components/commons/Header.js
  src/components/commons/Sidebar.js
  src/components/contents/ApprovalBox.js
  src/components/contents/ButtonGroup.js
  src/components/contents/Editor.js
  src/components/contents/ScheduleBox.js
  src/components/contents/TitleAndFile.js
  src/pages/Main.js
  src/pages/notices/InsertNotice.js
  src/pages/notices/Notices.js
Labels: 기능구현

#8 [Feature-0507](#7) - notice- 공지목록조회
  public/index.html
  src/apis/Api.js
  src/apis/NoticeAPICalls.js
  src/components/contents/BootstrapTable.js
  src/components/contents/Editor.js
  src/components/contents/TitleAndFile.js
  src/index.js
  src/modules/NoticeModule.js
  src/modules/index.js
  src/pages/Main.js
  src/pages/notices/InsertNotice.js
  src/pages/notices/Notices.js
  src/style.css
  src/utils/tokenUtils.js
Labels: 기능구현

#13 [Feature-0507](#11) - calendar - 부서별 일정 목록 조회
  package-lock.json
  package.json
  src/App.js
  src/Store.js
  src/apis/Api.js
  src/apis/ScheduleAPICalls.js
  src/components/form/ScheduleForm.js
  src/modules/ScheduleModule.js
  src/modules/index.js
  src/pages/schedules/calendar.js
Labels: 기능구현

#16 [Feature-0508](#15) - 리액트 로그인 구현
  README.md
  package-lock.json
  src/App.js
  src/apis/Api.js
  src/apis/MemberAPICalls.js
  src/components/commons/Header.js
  src/modules/MemberModule.js
  src/modules/index.js
  src/pages/Main.js
  src/pages/members/Login.js
Labels: 기능구현

#18 [Feature-0508](#17) - 메일 - 받은 메일 조회
  package-lock.json
  src/App.js
  src/apis/Api.js
  src/apis/MailAPICalls.js
  src/components/commons/Header.js
  src/components/items/mails/ReceiveMail.js
  src/components/items/mails/SendMail.js
  src/components/lists/MailList.js
  src/modules/MailModule.js
  src/modules/index.js
  src/pages/mails/InsertMail.js
  src/pages/mails/Mail.js
  src/pages/mails/MailDetail.js
Labels: 기능구현

#19 [Feature-0508](#5) - Approvals - 전자결재목록
  src/App.js
  src/apis/Api.js
  src/apis/ApprovalAPICalls.js
  src/components/approvals/AppCategory.js
  src/components/approvals/AppCategory.module.css
  src/components/approvals/AppList.js
  src/components/approvals/ApprovalDetail.js
  src/components/commons/Sidebar.js
  src/modules/ApprovalModule.js
  src/modules/index.js
  src/pages/approvals/ApprovalDetail.js
  src/pages/approvals/Approvals.js
  src/pages/approvals/Approvals.module.css
  src/pages/approvals/InsertApproval.js
Labels: 기능구현

#21 [Feature-0508](#20) - notice- 공지 상세조회
  README.md
  package-lock.json
  src/App.js
  src/apis/Api.js
  src/apis/NoticeAPICalls.js
  src/components/contents/BootstrapTable.js
  src/components/contents/ButtonGroup.js
  src/components/contents/Editor.js
  src/components/contents/PaginationButtons.js
  src/components/form/InsertNoticeForm.js
  src/components/items/notices/Notice.js
  src/modules/NoticeModule.js
  src/pages/Main.js
  src/pages/notices/InsertNotice.js
  src/pages/notices/NoticeDetail.js
  src/pages/notices/Notices.js
  src/style.css
Labels: 기능구현

#26 [Feature-0509](#23) - calendar - 부서 일정 등록시 자동으로 렌더링하여 목록 조회
  package-lock.json
  package.json
  src/components/form/ScheduleForm.js
  src/pages/schedules/calendar.js
Labels: 디벨롭

#30 [Feature-0509](#29) - 내정보 조회
  public/img/1cb643b156124860ac42046fa9afd8a9.png
  public/img/8f3fd818208e44f6abd7b7116f9f79e1.png
  public/img/9872d59316cb4db083b8d6d4dfea3111.png
  public/img/a56f9044be1845dab9d34a257762a69a.png
  public/img/b6123f0a955d46038005530ca2cb6acd.png
  public/img/cc5684b5f09b4b068b3bde1c6e9a0df9.png
  public/img/eeaa6dc9ce784000a65d92e20649e7fa.png
  public/img/f67d2cce341e4e9e91b15b43c53c4f57.png
  public/index.html
  public/logo.ico
  public/logo1.ico
  public/logo2.ico
  public/logo3.ico
  public/manifest.json
  src/App.js
  src/apis/Api.js
  src/apis/MemberAPICalls.js
  src/apis/ScheduleAPICalls.js
  src/components/commons/Header.js
  src/pages/members/MyPage.js
Labels: 기능구현

#31 [Feature-0510](#12) - calendar - 부서별 일정 상세조회 컴포넌트 생성
  src/apis/ScheduleAPICalls.js
  src/components/form/ScheduleDetail.js
  src/components/form/ScheduleForm.js
  src/modules/ScheduleModule.js
  src/pages/schedules/calendar.js
Labels: 기능구현

#34 [Feature-0510](#1 #7 #20 #4 ) - notice - 메인 공지조회, 공지 목록조회, 공지 상세조회, 공지 등록
  public/img/58fe5952b4ee48e59283c1a7a238a230.png
  src/apis/Api.js
  src/apis/NoticeAPICalls.js
  src/components/contents/Editor.js
  src/components/contents/FormatDate.js
  src/components/contents/FormatDateTime.js
  src/components/contents/TitleAndFile.js
  src/components/form/InsertNoticeForm.js
  src/components/items/notices/Notice.js
  src/pages/Main.js
  src/pages/notices/NoticeDetail.js
  src/pages/notices/Notices.js
Labels: 기능구현, 디벨롭

#36 [Feature-0510](#12) - calendar - 상세 조회에서 삼항연산자를 통해 인풋창 보이게 구현
  README.md
  src/apis/ScheduleAPICalls.js
  src/components/form/ScheduleDetail.js
  src/components/form/ScheduleForm.js
  src/modules/ScheduleModule.js
  src/pages/schedules/calendar.js
Labels: 기능구현, 디벨롭

#38 [Feature-0510] - {InsertMember} 사원등록 #37
  public/img/loginLogo.png
  src/App.js
  src/apis/Api.js
  src/pages/members/InsertMember.js
  src/pages/members/Login.js
  src/pages/members/Member.js
  src/pages/members/Members.js
Labels: 기능구현

#44 [Feature-0511](#7) - notice - 공지 목록조회 검색기능 수정
  src/apis/NoticeAPICalls.js
  src/components/contents/SearchBar.js
  src/components/items/notices/Notice.js
  src/pages/notices/Notices.js
Labels: 기능구현, 디벨롭

#47 [Feature-0512](#45) - 메일 - 메일 상세
  package-lock.json
  src/App.js
  src/apis/MailAPICalls.js
  src/components/commons/Header.js
  src/components/contents/CheckBootstrapTable.js
  src/components/form/MailForm.js
  src/components/items/mails/MailContent.js
  src/components/lists/mails/ReceiveMail.js
  src/components/lists/mails/SendMail.js
  src/modules/MailModule.js
  src/pages/mails/Mail.js
  src/pages/mails/MailDetail.js
  src/pages/mails/MailReply.js
Labels: 기능구현

#50 [Feature-0512](#49) - schedule - 부서별 일정 삭제
  src/apis/Api.js
  src/apis/ScheduleAPICalls.js
  src/components/form/ScheduleDetail.js
  src/pages/schedules/calendar.js
Labels: 기능구현

#52 [Feature-0512](#51) - calender - 부서별 일정 수정
  src/components/form/ScheduleDetail.js
  src/pages/schedules/calendar.js
Labels: 기능구현

#55 [Feature-0513](#53) - calendar - 메인 화면에서 부서별 일정 조회
  src/App.js
  src/apis/Api.js
  src/apis/ReserveAPICalls.js
  src/apis/ScheduleAPICalls.js
  src/components/commons/Sidebar.js
  src/components/form/InsertNoticeForm.js
  src/components/form/ScheduleDetail.js
  src/modules/ReserveModule.js
  src/modules/ScheduleModule.js
  src/modules/index.js
  src/pages/Main.js
  src/pages/reserves/Reserve.js
  src/pages/schedules/calendar.js
Labels: 기능구현

#56 [Feature-0513] - 매일 - 메일 디벨롭(약간)
  src/App.js
  src/apis/MailAPICalls.js
  src/components/contents/MailTable.js
  src/components/form/MailForm.js
  src/components/items/mails/MailContent.js
  src/components/lists/mails/ReceiveMail.js
  src/components/lists/mails/SendMail.js
  src/modules/MailModule.js
  src/pages/mails/Mail.js
  src/pages/mails/MailDetail.js
  src/pages/mails/mail.css
Labels: 디벨롭

#59 [Feature-0513](#58) - reserve - 자원 예약 목록 조회
  src/apis/ReserveAPICalls.js
  src/pages/Main.js
  src/pages/reserves/Reserve.js
Labels: 기능구현

#62 [Feature-0513](#37) - 사원등록
  public/img/00decb40410f4247abab2a5410dd9b3a.png
  public/img/05366c67d5544274bb85ae9915739e11.png
  public/img/3bce85df87f64eae96731a623ad5c24f.png
  public/img/958a1d0b04674fa695fe34bec7909d5c.png
  public/img/a28c0beec5924e648ee1ce9a12141154.jpg
  public/img/needFile.png
  src/apis/Api.js
  src/apis/MemberAPICalls.js
  src/pages/members/InsertMember.js
  src/pages/members/Login.js
  src/pages/members/Member.js
Labels: 기능구현

#64 [Feature-0514](#7 #20 #4 #9) - notice - 공지 유효성(권한), 파일 업로드,다운로드
  public/img/0f623b176a534289be5c709df55c1eee.m1.png.png
  public/img/1a26eb12156c4b0d9774bce49c5249b4.캡처1.PNG.PNG
  public/img/256f2b82aa1445f7997297cceb7b6634.m1.png.png
  public/img/2cca227c2b3d43a387fb34cc55486a46.details1.PNG.PNG
  public/img/3c5c28724a1c470c9cb55db79cd8b44e.캡처1.PNG.PNG
  public/img/47a666d959c44a6ab3c63ccc35e99a62.m1.png.png
  public/img/9210c5e70825474fa4e2d8215ec1802d.details1.PNG.PNG
  public/img/cadb4eee976f470cab8c8fa3d2007daf.캡처1.PNG.PNG
  src/apis/NoticeAPICalls.js
  src/components/commons/Sidebar.js
  src/components/contents/Editor.js
  src/components/form/InsertNoticeForm.js
  src/components/form/UpdateNoticeForm.js
  src/components/items/notices/Notice.js
  src/pages/notices/NoticeDetail.js
  src/pages/notices/Notices.js
  src/style.css
Labels: 기능구현, 디벨롭

#67 [Feature-0510] - {InsertMember, Members} 사원등록 #37
  README.md
  package-lock.json
  package.json
  public/img/15acd7eb6e0540318b842587f1083b64.png
  public/img/241099dbc69b416eba67db00d4062ad4.png
  public/img/36544d67bdb14c2ca4702671963790a2.png
  public/img/36dbadd285c54e7fa40c304dfb8bf017.png
  public/img/8f8d95701fd141d98edf45760727bf98.png
  public/img/b6cc8ed5e74a4cdb8a27a936b03d6dd9.png
  public/img/bc13447c43ff46ce82bacba32edfd934.png
  public/img/c8ca238b4cf64a349b2416541b46609a.png
  public/img/ea245ebf3cb6454ba808837760d28070.jpg
  public/img/f6402cc82cfa484f96bbcfa0dc055099.png
  src/apis/MemberAPICalls.js
  src/pages/members/InsertMember.js
  src/pages/members/Member.js
  src/pages/members/Members.js
  src/pages/members/MyPage.js
Labels: 기능구현, 에러

#70 [Feature-0514] - {MemberController} 페이징없는 사원전체조회 추가
  public/img/066cc8424bed4b818a3d04f86f42e266.png
  public/img/19e47e92efd746129e22f7ab92469c59.memberImage.jpg.jpg
  public/img/2d01ed4bb66446459eef17427d5f73fe.png
  public/img/341fec8450624212ad8916d4e80e228c.png
  public/img/3afde5ca17124fc59924414cf0415b93.ketchup.png.png
  public/img/4386901a0bea4468b640fc3035f1c642.png
  public/img/4ccc79a5a9c847cab9652b9c668b78a7.memberImage.jpg.jpg
  public/img/6990081b4e334fb0ad3b31b12706f2db.jpg
  public/img/74346428b59343b393a82594a7f2e2e5.png
  public/img/824b9ebfaf3542bd8586f6d607c6ca55.png
  public/img/839ed21295a74e909f9e37e3afd60c27.jpg
  public/img/9a861a80c5684a56944d9086f8373f8d.jpg
  public/img/a2919a79f2054c7f82d5a328dfaddd4f.png
  public/img/c0611e39170143588d1ecc0045fa3315.ico
  public/img/c7c7680c93ae4d3d94b89f9ee2cf1ab0.jpg
  public/img/ceed8901513b47cba147bec9d7dcfba1.png
  public/img/e515a822b952487d80e76473def5198b.jpg
  src/apis/MemberAPICalls.js
  src/pages/members/InsertMember.js
  src/pages/members/Members.js
Labels: 기능구현, 디벨롭

#72 [Feature-0514](Member)퇴사처리 기능구현
  public/img/9b278838c0694789beb90145b4a13e9b.jpg
  src/apis/MemberAPICalls.js
  src/pages/members/Member.js
Labels: 기능구현

#73 [Feature-0514](#58) - reserve - 자원 예약 목록 조회 성공
  src/pages/reserves/Reserve.js
Labels: 기능구현, 디벨롭

#75 [Feature-0515](#74) - 메일 - 메일 읽음 상태 변경
  src/App.js
  src/apis/MailAPICalls.js
  src/components/form/MailForm.js
  src/components/items/mails/MailTable.js
  src/components/items/mails/MailTableBody.js
  src/components/lists/mails/ReceiveMail.js
  src/components/lists/mails/SendMail.js
  src/modules/MailModule.js
  src/pages/mails/Mail.js
  src/pages/mails/mail.css
Labels: 기능구현

#77 [Feature-0510](#76) - app - 로그인 후 main페이지, 로그아웃 후 login페이지 이동
  public/img/4d167452a3574e41a8f5778df48a16e8.pikachu.png.png
  public/img/67ed45e5193641cb97fdc261fcf2f734.png
  public/img/708aaebed8604ed183651886eedce1f1.pikachu.png.png
  public/img/b8a95676df2a44fa8a46747a54fc43b6.png
  public/img/d39f078a597f4a44a12dee7a037154a7.png.png
  public/img/de2b737a46794192b75641934bafead2.pikachu.png.png
  public/img/e9602bfbfbc84d58a6ad875bd1885d61.pikachu.png.png
  src/App.js
  src/components/commons/Header.js
  src/components/commons/Sidebar.js
  src/pages/Error.js
  src/pages/members/Login.js
Labels: 기능구현

#82 [Feature-0516](#80 #81) - 메일/자원 관리 - 메일 발송 취소/자원 조회
  package-lock.json
  src/App.js
  src/apis/MailAPICalls.js
  src/apis/ResourceAPICalls.js
  src/components/items/mails/MailTableBody.js
  src/components/items/mails/SendCancelModal.js
  src/components/lists/resources/ResourceList.js
  src/modules/MailModule.js
  src/modules/ResourceModule.js
  src/modules/index.js
  src/pages/resources/Resources.js
Labels: 기능구현

#84 [Feature-0516] - {InsertMembers} 사원등록시 이메일 유효성 검사 구현
  public/img/03576331162c4d8fbd2fcb5308a38b8e.png
  public/img/06c86c8e2fbb4e7296152236b68fd4a3.png
  public/img/16f848fb0c034e1e901ba65e97e0ba6f.png
  public/img/1e1e78b9adae435aabc080bea3b34585.jpg
  public/img/273f906afb094cbe91fa311ccadc56fc.png
  public/img/2ad488f9cfa84838918a5d9c9affb53e.png
  public/img/3f36cf4387fc4dbab011ba0af1fe2ce9.png
  public/img/4e0e3697d3f0494e81fa5ffd1a398304.png
  public/img/4f1a28b727cd478e8dbd545ebd1046bc.png
  public/img/5df353bb55c048abad3c99a92afc8448.png
  public/img/5e06c2ddcea94c6ab85da01b301196a3.png
  public/img/626e4248facb4ee0868afbbeb6d5059c.png
  public/img/6dae93bc7f944aabbd866390ae85a425.png
  public/img/cb3feb3e33e848d899c712c7229067a8.jpg
  public/img/d9f8b080eca24618b8bd4b4cc83c676b.png
  public/img/daf53bb14e32446dad7cb570cf81649f.png
  public/img/dd70996640a04e309df1e628110fad05.png
  public/img/e8b67a4a715243e8ae861d3b73a72af0.png
  public/img/f2c0872bea6c4d23a549bb865cfe5afc.png
  src/App.js
  src/apis/MemberAPICalls.js
  src/components/commons/Header.js
  src/pages/members/InsertMember.js
  src/pages/members/Member.js
Labels: 기능구현

#85 [Feature-0517](#83) - 메일 - 메일 삭제
  src/apis/MailAPICalls.js
  src/components/items/mails/MailContent.js
  src/components/items/mails/MailDeleteModal.js
  src/components/items/mails/MailTable.js
  src/pages/mails/Mail.js
  src/pages/mails/MailDetail.js
Labels: 기능구현

#86 [Feature-0517](#37) - 사원등록 유효성 검사/부서,직급 선택
  public/img/61971ace893842848f5a1c7af587848e.png
  public/img/8a05406baeb8490daba04b7abe23c296.png
  public/img/caad5aaa365a47efa03086395f37a84c.png
  src/apis/MemberAPICalls.js
  src/modules/DepartmentModule.js
  src/modules/MemberModule.js
  src/modules/PositionModule.js
  src/modules/index.js
  src/pages/members/InsertMember.js
  src/pages/members/Members.js
Labels: 기능구현, 디벨롭

#88 [Feature-0517](#37) - 사원등록 유효성 검사수정 #86
  public/img/a90ec733b82645158e56e4bd7c3d4950.png
  src/pages/members/InsertMember.js
Labels: 디벨롭

#90 [Feature-0517]() - 메일 - 메일 작성
  src/apis/MailAPICalls.js
  src/components/commons/Sidebar.js
  src/components/form/MailForm.js
  src/components/items/mails/MailDeleteModal.js
Labels: 기능구현

#92 [Feature-0517] - {App.js} login 이후 라우팅 에러
  src/App.js
  src/apis/MemberAPICalls.js
  src/components/commons/Header.js
  src/pages/members/InsertMember.js
  src/pages/members/Login.js
  src/style.css
Labels: 디벨롭

#93 [Feature-0518](#41 #42) - board - 게시물 등록, 수정
  package-lock.json
  public/img/8277b8b70d5a4b5aa332b9348a1ac55f.m4.png.png
  public/img/9da95b55c9424a4d81f972be90b27540.png
  public/img/f46bc3a1b1ca4f97bc9090457df123d3.png
  src/App.js
  src/apis/BoardAPICalls.js
  src/components/form/InsertBoardForm.js
  src/components/form/UpdateBoardForm.js
  src/modules/index.js
  src/pages/boards/Boards.js
Labels: 기능구현

#97 [Feature-0520](#58 ) - reserve - 자원예약 목록 조회
  public/img/045dd7f16ec6404194472c94636174f1.png
  public/img/07592464203b471a948a67e4eacdb529.png
  public/img/638b1b4b6db8436fa7b2e8028e90a58e.png
  public/img/7655f9c91b62431f88962bc1b68f23e5.png
  public/img/c1147732d6c149698f8b4dc665f39fe7.png
  public/img/d5c065ab15dd4c229a30395eafe466bd.png
  public/index.html
  src/pages/Main.js
  src/pages/reserves/Reserve.js
  src/pages/reserves/ReserveDateSelect.js
  src/pages/reserves/ResourceCategorySelect.js
  src/pages/schedules/calendar.js
Labels: 기능구현, 디벨롭

#99 [Feature-0520] - {Members} 사원정보 수정/직급정보 조회/조직정보 조회
  public/img/0ebecef8d8784992951dfc700a58fa28.png
  public/img/0eeb67359b614ab08aaf8fdd6e93944e.png
  public/img/1413c8fa4dc84be9bbe4ec8fe7f1409e.png
  public/img/2fed2bc32efb49daa593953fe94b38e8.png
  public/img/3c5cc10fa4214dc0884e4d9708ca5a69.png
  public/img/3d08ded4cfaa4f1dafb5559ecbef6723.png
  public/img/5517ac64a6e54324bda1fc9681ac09db.png
  public/img/6eaf35c4e28d497f9459cbd67752a43c.png
  public/img/71402f21f81d42388af36e2df4604754.png
  public/img/79bfe748b81b485195be6d1461341175.png
  public/img/7bd44d995ddd483bbe87c388676694b2.png
  public/img/7f489017006843ceacfc4bab60465349.png
  public/img/852a51a55f8344168d6d5035c64e6264.png
  public/img/9082e7b1a9c24a209c12c71d9edd0970.png
  public/img/aa53e786de3c4090a31a5dbd2f327b39.png
  public/img/b2458dc1918449c09507d0ee3e6c7dfd.png
  public/img/ca359ef22d1a4bd79e83275e68118e35.png
  public/img/e078bf0b40414c1093af6444f478a135.png
  public/img/e61db0fe691c4e64ba3a2e914a6191db.png
  public/img/f393a4ccf58149a09bd4bfb7715bab20.png
  public/img/f39b7af2b92c4c08971c12aad0fadc95.png
  src/App.js
  src/apis/Api.js
  src/apis/MemberAPICalls.js
  src/components/commons/Sidebar.js
  src/modules/MemberModule.js
  src/pages/members/Departments.js
  src/pages/members/InsertMember.js
  src/pages/members/Login.js
  src/pages/members/Member.js
  src/pages/members/Positions.js
Labels: 기능구현, 디벨롭

#104 [Feature-0520](#103) - Reserve - 자원예약 상세조회
  public/img/0760ae39684d471e969cbdbe9fd4e664.png
  src/apis/ReserveAPICalls.js
  src/apis/ResourceAPICalls.js
  src/components/form/InsertReserveForm.js
  src/components/form/ReplyMailForm.js
  src/components/form/ReserveDetail.js
  src/modules/ReserveModule.js
  src/pages/reserves/Reserve.js
Labels: 기능구현

#106 [Feature-0520](#39 #89) - board - 부서별 자료실 게시물 목록조회 페이징
  public/img/69bcd77943a1450f8b15daed576718ef.png
  public/img/9fa02dab40ef44779f490dbb7551423e.png
  public/img/a07108d8608745e780878d20dc36a69b.png
  public/img/a11a442a971749f298900ce1def36d1b.png
  public/img/e91bb612c2e4482e82d70c0d5aa47529.png
  public/img/ef9a1ee42a194a65a4907beb38842101.png
  src/apis/BoardAPICalls.js
  src/components/contents/PaginationButtons.js
  src/components/contents/SearchBar.js
  src/components/items/boards/Board.js
  src/pages/boards/Boards.js
  src/pages/notices/Notices.js
  src/style.css
Labels: 기능구현, 디벨롭

#107 [Feature-0521] - 메일/자원 - 메일 뒤로가기 에러 수정, 자원 등록 추가
  src/apis/ResourceAPICalls.js
  src/components/form/InsertResourceForm.js
  src/components/form/MailForm.js
  src/components/form/ReplyMailForm.js
  src/components/form/UpdateResourceForm.js
  src/components/items/mails/MailContent.js
  src/components/items/mails/SendCancelModal.js
  src/components/items/resources/RscDetailContent.js
  src/components/items/resources/RscDetailModal.js
  src/components/items/resources/RscModal.js
  src/components/items/resources/RscRegistModal.js
  src/components/lists/mails/SendMail.js
  src/components/lists/resources/ResourceList.js
  src/modules/ResourceModule.js
  src/pages/mails/MailReply.js
  src/pages/resources/resource.css
  src/style.css
Labels: 기능구현, 에러

#108 [Feature-0521](#39 #40) - board - 게시물 목록조회, 상세조회 수정
  public/img/1ea63d5e0a464fa4b249f7272ff5cb5c.png
  public/img/6726b2eb976945388d46dbf69c3bb6fd.png
  public/img/776fdd7046ce4c3398549e58d663a630.png
  public/img/d01da119c8064ff88fd1727219d3f820.png
  public/img/f25c0b8f2e3f404d8a5cddd7751d2636.png
  src/components/commons/Header.js
  src/components/form/ReplyMailForm.js
  src/components/items/boards/Board.js
  src/pages/boards/Boards.js
  src/pages/notices/Notices.js
Labels: 디벨롭

#110 [Feature-0521](#105 ) - InsertReserveForm - 자원예약 등록 1차 완료
  public/img/1fb9029c0b1249fbaa87608a204c8abb.png
  src/components/form/InsertReserveForm.js
  src/components/form/ReserveDetail.js
  src/pages/reserves/Reserve.js
Labels: 기능구현

#111 [Feature-0521] - {Postions/PositionForm} 직급 추가,직급 삭제
  src/apis/MemberAPICalls.js
  src/components/form/PositionForm.js
  src/components/form/ReserveDetail.js
  src/modules/PositionModule.js
  src/pages/members/Positions.js
Labels: 기능구현

#115 [Feature-0521](#105 ) - InsertReserveForm - 자원예약 등록 업데이트
  src/components/form/InsertReserveForm.js
  src/components/form/ReserveDetail.js
  src/pages/reserves/Reserve.js
Labels: 기능구현, 디벨롭

#119 [Feature-0521](OrganizationChart) - 조직도 추가
  package-lock.json
  package.json
  public/img/0ab9b8ffcac74ee0b46e5530cf220b8c.png
  public/img/0d27fa3544cf44688be3c7cc884e52ee.png
  public/img/58af058fe5184dfebec10b5fb7772a96.png
  public/img/95c6dc20aeed4e8798b7c11d0972af2f.png
  public/img/approvals/257f48b3124c472a853938eebf4bcef7.png
  public/img/approvals/9bb6e206adaf4a0297b3bf1d192f24f8.jpg
  public/img/b8d42934941740f0971e899b33a96d3d.png
  public/img/c83e7668cc0943c5996bda3b47d26b21.png
  public/img/cc5f20091faa47cdbf0e100cfb0a6738.png
  src/App.js
  src/apis/MemberAPICalls.js
  src/components/commons/Sidebar.js
  src/components/contents/SearchBar.js
  src/components/form/InsertReserveForm.js
  src/components/form/MailForm.js
  src/pages/members/InsertMember.js
  src/pages/members/Member.js
  src/pages/members/Members.js
  src/pages/members/OrganizationChart.js
  src/pages/members/TreePractice.js
  src/tree.css
Labels: 기능구현

#123 [Feature-0522](#122) - ReserveDetail - 자원예약 UI/UX
  README.md
  package-lock.json
  package.json
  public/img/searchConditionRequired.png
  src/components/scrolls/Arrow.js
  src/components/scrolls/Block.js
  src/components/scrolls/Scrolls.js
  src/pages/reserves/Reserve.css
  src/pages/reserves/Reserve.js
  src/pages/reserves/ReserveDateSelect.js
  src/pages/reserves/ResourceCategorySelect.js
Labels: 기능구현

#125 [Feature-0522] - {TreePractice} 조직도 구현 #124
  README.md
  package-lock.json
  package.json
  src/App.js
  src/pages/members/OrganizationChart.js
  src/pages/members/TreePractice.js
  src/tree.css
Labels: 기능구현

#127 [Feature-0522](#122 ) - ReserveDetail - 자원예약 UI/UX 가로 스크롤 및 좌우버튼 생성
  README.md
  package-lock.json
  package.json
  src/components/scrolls/Arrow.js
  src/components/scrolls/Block.js
  src/components/scrolls/Scrolls.css
  src/components/scrolls/Scrolls.js
  src/pages/reserves/Reserve.js
Labels: 디벨롭

#128 자원 수정, 자원 삭제, 자원 권한 추가
  src/apis/ResourceAPICalls.js
  src/components/contents/ButtonGroup.js
  src/components/form/InsertResourceForm.js
  src/components/form/MailForm.js
  src/components/form/ReserveDetail.js
  src/components/form/UpdateResourceForm.js
  src/components/items/mails/MailContent.js
  src/components/items/mails/MailTable.js
  src/components/items/resources/RscDetailContent.js
  src/components/items/resources/RscModal.js
  src/components/lists/resources/ResourceList.js
  src/modules/ResourceModule.js
  src/pages/Main.js
  src/pages/mails/Mail.js
  src/pages/mails/mail.css
  src/pages/resources/Resources.js
  src/pages/resources/resource.css
  src/style.css
Labels: 기능구현, 디벨롭

#130 [Feature-0522](#20 #40) - board, notice - 공지 상세조회(이전, 다음글 이동), 공지 상세조회(파일 삭제), 게시물 상세조회(이전, 다음글 이동), 게시물 상세조회(파일 삭제)
  public/img/0baf566f50e04f0fbb059215ba967b51캡처3.PNG.PNG
  public/img/250a91bcab3c46d8a10824789f86713a.m3.png.png
  public/img/296764c273bf47eaa1cb41c2f4d74c6f.m1.png.png
  public/img/2eda96f9695c41129820fbc95c7ce44e.m3.png.png
  public/img/7bf01c95fb004214bc2152417e8235c4.png
  public/img/7c5db59c5f074e1f94f609562b69df20.png
  public/img/eecca412b19643cabfd1547607e0e5c3.details1.PNG.PNG
  public/img/fca5d3ccc5d2450492f8387b91edd993.m4.png.png
  public/img/m2.pngca6f7fe6520749fbb7444f228a668a9e.png
  public/img/m5.png9de7112aa23245c18c67b2705e680372.png
  src/apis/BoardAPICalls.js
  src/apis/NoticeAPICalls.js
  src/components/contents/ApprovalBox.js
  src/components/contents/BootstrapTable.js
  src/components/contents/PaginationButtons.js
  src/components/form/ReplyMailForm.js
  src/components/form/UpdateBoardForm.js
  src/components/form/UpdateNoticeForm.js
  src/components/items/boards/Board.js
  src/components/items/notices/Notice.js
  src/pages/Main.js
  src/pages/boards/Boards.js
  src/pages/notices/Notices.js
  src/style.css
Labels: 디벨롭

#133 [Feature-0523](#6 #5 #25 ) - 기안등록 - 기안등록
  package-lock.json
  package.json
  public/img/186f2bf30bbb4138851fb3b20b13be93.png
  public/img/1db492ab11a941588b2aead3539ccc99.png
  public/img/7e5d45e37deb4a9fa21709a436d194d7.png
  public/img/approvals/0eb6372f8abc481ea7e0c110d50f3a0a.webp
  public/img/approvals/7cf30fe2a76d4322b84789709ef925d1 2.png
  public/img/approvals/7cf30fe2a76d4322b84789709ef925d1.png
  public/img/approvals/880048f714d24a7fbca1c223ecb8bbeb.webp
  public/img/approvals/a72bbf0859f14e51add1384cfcc12826.webp
  public/img/approvals/f3b7d75bab84463c8949cb18096db0c6.webp
  public/img/e712bf0b101d48888c77c2cdf6bfb06b.png
  public/img/edc0449ef3314358a10f72db582beb76.png
  src/apis/ApprovalAPICalls.js
  src/components/approvals/AppCategory.js
  src/components/approvals/AppLineModal.js
  src/components/approvals/AppList.js
  src/components/approvals/RefLineModal.js
  src/pages/Main.js
  src/pages/approvals/ApprovalDetail.js
  src/pages/approvals/Approvals.js
  src/pages/approvals/Approvals.module.css
  src/pages/approvals/InsertApproval.js
  src/style.css
Labels: 기능구현, 디벨롭

#135 [Feature-0523] - {Positions} 직급 수정 #134
  README.md
  public/images/mainImage.png
  src/App.js
  src/apis/MemberAPICalls.js
  src/apis/NoticeAPICalls.js
  src/components/form/PositionForm.js
  src/modules/PositionModule.js
  src/pages/Main.js
  src/pages/members/InsertMember.js
  src/pages/members/Members.js
  src/pages/members/OrganizationChart.js
  src/pages/members/Positions.js
  src/pages/members/TreePractice.js
  src/style.css
Labels: 기능구현, 디벨롭

#136 메일, 자원 수정
  src/apis/MailAPICalls.js
  src/apis/ResourceAPICalls.js
  src/components/contents/SearchBarValue.js
  src/components/items/mails/MailDeleteModal.js
  src/components/items/mails/MailTable.js
  src/components/items/resources/RscDetailContent.js
  src/components/items/resources/RscModal.js
  src/components/lists/mails/ReceiveMail.js
  src/components/lists/mails/SendMail.js
  src/components/lists/resources/ResourceList.js
  src/pages/mails/Mail.js
  src/pages/mails/mail.css
  src/pages/resources/Resources.js
Labels: 디벨롭

#137 [Feature-0523](#1 #89) - board, 컴포넌트- 게시물 삭제 모달생성, css, 컴포넌트 수정
  public/img/approvals/569055f89d9e4a4e98606e67ca8356e8.png
  public/img/approvals/95a1c6cbd57b4d7eae1d567eaf787202.png
  public/img/approvals/f23422d9731b4075bb72f6e28dc7f9ab.png
  src/components/commons/Sidebar.js
  src/components/contents/BootstrapTable.js
  src/components/contents/SearchBar.js
  src/components/form/PositionForm.js
  src/components/items/boards/Board.js
  src/components/items/boards/DeleteModal.js
  src/components/items/mails/MailDeleteModal.js
  src/components/items/mails/SendCancelModal.js
  src/components/items/notices/Notice.js
  src/components/lists/resources/ResourceList.js
  src/pages/mails/Mail.js
  src/pages/members/Positions.js
  src/pages/notices/Notices.js
  src/pages/resources/Resources.js
  src/pages/resources/resource.css
  src/style.css
Labels: 기능구현, 디벨롭

#138 [Feature-0523](#122 ) - ReserveDetail, InsertReserveForm - 자원예약 등록/수정 유효성 검사, UI/UX
  README.md
  package-lock.json
  package.json
  src/components/form/InsertReserveForm.js
  src/components/form/ReserveDetail.js
  src/components/scrolls/Block.js
  src/pages/Main.js
  src/pages/reserves/Reserve.css
  src/pages/reserves/Reserve.js
  src/pages/reserves/ReserveDateSelect.js
  src/pages/reserves/ResourceCategorySelect.js
Labels: 기능구현, 디벨롭

#139 [Feature-0524]() - Mail/Resource - 메일 수정, 자원 페이징
  src/apis/MailAPICalls.js
  src/apis/ResourceAPICalls.js
  src/components/contents/SearchBarValue.js
  src/components/form/UpdateResourceForm.js
  src/components/items/boards/DeleteModal.js
  src/components/items/mails/MailContent.js
  src/components/items/mails/MailDeleteModal.js
  src/components/items/mails/MailTable.js
  src/components/items/resources/RscDetailContent.js
  src/components/items/resources/RscModal.js
  src/components/lists/mails/ReceiveMail.js
  src/components/lists/mails/SendMail.js
  src/components/lists/resources/ResourceList.js
  src/pages/mails/Mail.js
  src/pages/mails/mail.css
  src/pages/resources/Resources.js
Labels: 디벨롭

#141 [Feature-0524](#20 #140) - notice, comment- 공지 상세조회 에러 수정, 게시물 댓글 api, module 생성
  package-lock.json
  package.json
  src/apis/CommentAPICalls.js
  src/apis/NoticeAPICalls.js
  src/components/items/notices/Notice.js
  src/modules/CommentModule.js
  src/modules/index.js
  src/pages/notices/Notices.js
Labels: 기능구현, 에러

#143 [Feature-0524] - {Departments} 부서 등록
  public/img/53364d00708a4397ba8e429b1da5160d.png
  public/img/74c63c5be3314c3ea5e29b2600c60593.png
  public/img/9f39618fed0f4853b1aa9a4c6398586c.png
  public/img/b5daf3a4e2d041c6a45b39c2a4f0535e.png
  public/img/b745a8e38c5546ce8f131896f0c4e790.png
  public/img/c40067120412476e9b7d938502c99fdf.png
  public/img/ef4341333ec6467b854aed33617cad4c.png
  src/apis/MemberAPICalls.js
  src/components/form/DepartmentForm.js
  src/modules/DepartmentModule.js
  src/pages/members/Departments.js
  src/pages/members/Positions.js
Labels: 기능구현

#144 [Bug-0524](issue 39) - boards 렌더링 오류 수정
  package-lock.json
  package.json
  src/pages/boards/Boards.js
Labels: 디벨롭, 에러

#145 [Feature-0524](#116) - ReserveDetail - 자원예약 상세조회 및 수정에 예약자 성명 화면 출력 완료
  public/img/approvals/686a6393734d41a8b7ff89f42f6aa124.png
  src/components/form/InsertReserveForm.js
  src/components/form/ReserveDetail.js
  src/components/form/ScheduleForm.js
  src/pages/approvals/ApprovalDetail.js
  src/pages/approvals/InsertApproval.js
  src/pages/reserves/InsertReserve.js
  src/pages/reserves/Reserve.js
  src/pages/schedules/calendar.js
Labels: 디벨롭

#147 [Feature-0524] - {Departments} 부서수정,부서삭제 기능구현
  public/img/249cdcb7503441d0b3670d1f48002d8b.스크린샷 2024-05-16 151419.png.png
  public/img/2ff6291a005d49e98fd947db23b9f9b5.png
  public/img/319c7764e93c49eb8e79608fdcc03ce9.png
  public/img/4c5f0b703cfd45408d347daca98768ee.png
  public/img/622f38cad3dd4cd3b9409d67270ee64c.png
  public/img/76a8edd920d9460e9d43f7967d6558be.png
  public/img/9f39618fed0f4853b1aa9a4c6398586c.png
  public/img/a86e39c18d1842b28e0a0d42e72fe288.png
  public/img/b745a8e38c5546ce8f131896f0c4e790.png
  public/img/c40067120412476e9b7d938502c99fdf.png
  public/img/ef4341333ec6467b854aed33617cad4c.png
  src/apis/MemberAPICalls.js
  src/components/form/DepartmentForm.js
  src/pages/members/Departments.js
  src/pages/members/InsertMember.js
  src/pages/members/Member.js
  src/pages/members/Members.js
  src/pages/members/MyPage.js
Labels: 기능구현

#148 [Feature-0524](issue 번호) - 전자결재 - 등록, 목록조회
  src/components/approvals/AppAlert.js
  src/components/approvals/AppLineModal.js
  src/components/approvals/AppList.js
  src/components/approvals/AppModal.module.css
  src/components/approvals/RefLineModal.js
  src/pages/approvals/ApprovalDetail.js
  src/pages/approvals/Approvals.js
  src/pages/approvals/Approvals.module.css
  src/pages/approvals/InsertApproval.js
Labels: 기능구현, 디벨롭

#153 [Feature-MMDD](#131) - calendar - 부서별 일정 UI 수정
  src/components/form/InsertReserveForm.js
  src/components/form/ScheduleDetail.js
  src/components/form/ScheduleForm.js
  src/pages/reserves/Reserve.js
  src/pages/reserves/ReserveDateSelect.js
  src/pages/reserves/ResourceCategorySelect.js
  src/pages/schedules/calendar.js
  src/style.css
Labels: 디벨롭

#155 [Feature-0526] - {MyPage} 비밀번호 수정 #154
  src/apis/MemberAPICalls.js
  src/components/form/UpdatePWForm.js
  src/modules/MemberModule.js
  src/pages/members/Departments.js
  src/pages/members/MyPage.js
Labels: 기능구현

#156 [Feature-0526](#131 ) - calendar - 일정 UI 수정
  src/components/form/DeleteReserveForm.js
  src/components/form/InsertReserveForm.js
  src/components/form/ReserveDetail.js
  src/components/form/ScheduleDetail.js
  src/pages/Main.js
  src/pages/reserves/Reserve.css
  src/pages/reserves/Reserve.js
  src/pages/schedules/calendar.js
Labels: 디벨롭

#157 [Feature-0527](issue 번호) - Mail/Resource - 메일 페이징 수정 진행, 자원 렌더링 수정
  src/apis/MailAPICalls.js
  src/components/form/InsertBoardForm.js
  src/components/form/InsertNoticeForm.js
  src/components/form/InsertResourceForm.js
  src/components/form/MailForm.js
  src/components/form/UpdateResourceForm.js
  src/components/items/mails/MailDeleteModal.js
  src/components/items/mails/MailTable.js
  src/components/items/resources/RscDetailContent.js
  src/components/items/resources/RscModal.js
  src/components/items/resources/RscRegistModal.js
  src/components/lists/mails/ReceiveMail.js
  src/components/lists/mails/SendMail.js
  src/components/lists/resources/ResourceList.js
  src/layouts/Layout.js
  src/pages/mails/Mail.js
  src/pages/mails/MailDetail.js
  src/pages/mails/mail.css
  src/pages/resources/Resources.js
  src/pages/resources/resource.css
Labels: 디벨롭

#159 [Feature-0527](#149 #150 #152) - comment - 댓글, 대댓글 등록, 조회, 삭제
  public/img/m2.pngf645f0a3676346299c7e8f33e498c97c.png
  src/apis/CommentAPICalls.js
  src/components/contents/BootstrapTable.js
  src/components/contents/DeleteModal.js
  src/components/contents/PaginationButtons.js
  src/components/form/InsertCommentForm.js
  src/components/form/NormalDeleteModalForm.js
  src/components/items/boards/Board.js
  src/components/items/comment/Comment.js
  src/components/items/notices/Notice.js
  src/modules/CommentModule.js
  src/pages/Main.js
  src/pages/boards/Boards.js
  src/pages/notices/Notices.js
  src/pages/resources/Resources.js
  src/style.css
Labels: 기능구현

#160 [Feature-0527]() - Mails - 읽지 않은 메일 조회, 메일 검색
  src/apis/MailAPICalls.js
  src/components/commons/Header.js
  src/components/commons/Sidebar.js
  src/components/contents/SearchBarValue.js
  src/components/form/MailForm.js
  src/components/form/UpdateResourceForm.js
  src/components/items/mails/MailDeleteModal.js
  src/components/items/mails/MailTable.js
  src/components/items/resources/RscModal.js
  src/components/lists/mails/ReceiveMail.js
  src/components/lists/mails/SendMail.js
  src/components/lists/resources/ResourceList.js
  src/layouts/Layout.js
  src/modules/MailModule.js
  src/pages/mails/Mail.js
  src/pages/mails/MailDetail.js
  src/pages/mails/mail.css
  src/pages/resources/Resources.js
Labels: 기능구현

#161 [Feature-0527](MyPage,Login) - 비밀번호수정,비밀번호찾기
  public/img/0ab2efdbae204839bfc89a2ed3b131a7.png
  public/img/e6b62f1e1a484d808d5aab5b6e94bde8.png
  public/img/ec9b1108433c40d888605b62d2352aa3.png
  src/App.js
  src/apis/Api.js
  src/apis/MemberAPICalls.js
  src/components/commons/Header.js
  src/components/form/UpdatePWForm.js
  src/pages/Main.js
  src/pages/members/FindPW.js
  src/pages/members/Login.js
Labels: 기능구현, 디벨롭

#162 [Feature-0527]() - 전자결재 - 결재참조선 선택삭제
  src/components/approvals/AppCategory.js
  src/components/approvals/AppCategory.module.css
  src/components/approvals/AppLine.module.css
  src/components/approvals/AppLineModal.js
  src/components/approvals/AppList.js
  src/components/approvals/AppModal.module.css
  src/components/approvals/RefLineModal.js
  src/pages/approvals/ApprovalDetail.js
  src/pages/approvals/Approvals.js
  src/pages/approvals/Approvals.module.css
  src/pages/approvals/InsertApproval.js
Labels: 기능구현, 디벨롭

#163 [Feature-0528] - {TreePractice} 조직도 수정
  public/img/2a63177a104647109ce75c1022109e9e.png
  public/img/5a8b24d15b8640bb8cd66cf47e480e19.png
  public/img/730b0434e9c54e559e3a3dfc1d573c50.png
  public/img/ec9b1108433c40d888605b62d2352aa3.png
  src/components/form/UpdatePWForm.js
  src/pages/members/FindPW.js
  src/pages/members/Login.js
  src/pages/members/TreePractice.js
Labels: 디벨롭

#164 [Feature-0528](#7 #39 #1) - 공지 목록, 자료실 목록 렌더링 이슈 수정 컴포넌트 콘솔로그 삭제 css 수정
  public/img/727b6de6a2454e5da7fbe9b8d3852b68.png
  src/App.js
  src/apis/BoardAPICalls.js
  src/apis/CommentAPICalls.js
  src/apis/NoticeAPICalls.js
  src/components/commons/Header.js
  src/components/commons/Sidebar.js
  src/components/contents/BootstrapTable.js
  src/components/contents/TitleAndFile.js
  src/components/form/DeleteReserveForm.js
  src/components/form/InsertBoardForm.js
  src/components/form/InsertCommentForm.js
  src/components/form/InsertNoticeForm.js
  src/components/form/NormalDeleteModalForm.js
  src/components/form/UpdateBoardForm.js
  src/components/form/UpdateNoticeForm.js
  src/components/items/boards/Board.js
  src/components/items/comment/Comment.css
  src/components/items/comment/Comment.js
  src/components/items/notices/Notice.js
  src/layouts/Layout.js
  src/modules/CommentModule.js
  src/pages/Error.js
  src/pages/Main.js
  src/pages/approvals/Approvals.js
  src/pages/boards/BoardDetail.js
  src/pages/boards/Boards.js
  src/pages/boards/InsertBoard.js
  src/pages/boards/UpdateBoard.js
  src/pages/members/Members.js
  src/pages/notices/InsertNotice.js
  src/pages/notices/Notices.js
  src/pages/notices/UpdateNotice.js
Labels: 디벨롭

#166 [Feature-0528] - {Members,OrganizationChart} 조직도 사진 추가, 부서별 접근권한 추가
  public/img/5565bd7e91144c9fad55888248cba0e8.png
  public/img/8999619162944228914f14d3c119e7f6.png
  src/App.js
  src/components/form/UpdatePWForm.js
  src/pages/members/Login.js
  src/pages/members/Member.js
  src/pages/members/Members.js
  src/pages/members/OrganizationChart.js
  src/pages/members/TreePractice.js
Labels: 디벨롭

#168 [Feature-MMDD](issue 번호) - 기능명 - 자원 상태 변경 또는 삭제 시 메일 내용 수정
  src/components/contents/DeleteModal.js
  src/components/form/MailForm.js
  src/components/form/UpdateResourceForm.js
  src/components/items/mails/MailDeleteModal.js
  src/components/items/mails/MailTable.js
  src/components/lists/mails/ReceiveMail.js
  src/pages/mails/Mail.js
  src/pages/mails/mail.css
  src/pages/resources/Resources.js
  src/style.css
Labels: 디벨롭

#171 [Feature-0529](#170) - calendar - 일정 필터링 추가
  public/img/7d3ac4f52dbc4fc49bfa2f718a1bdc2c.png
  src/components/form/InsertReserveForm.js
  src/components/form/ScheduleDetail.js
  src/components/form/ScheduleForm.js
  src/components/lists/subscriptions/SubscriptionList.js
  src/pages/members/MyPage.js
  src/pages/reserves/Reserve.css
  src/pages/schedules/calendar.js
Labels: 기능구현, 디벨롭

#173 [Feature-0529] - {DepartmentForm} 팀장추가, 조직도 개편 #172
  public/img/0edc27ca78d642cfab371d0f01632a7e.png
  public/img/15511f2303c24862b0237cf3a23cbae3.png
  public/img/1fa81459de9a4331a5f257fd08dc88eb.png
  public/img/310994ce573845daaa55ae8756da4e6e.png
  public/img/31c5500dcd204c2fba594f098e5d7f23.png
  public/img/37457af754e14f4baf4c271dfbf408b1.png
  public/img/4b7db9a233fe4025a119c4f0f5a36ce0.png
  public/img/5829fde792214b72a7ae4f10b15e1fec.png
  public/img/727b6de6a2454e5da7fbe9b8d3852b68.png
  public/img/7c186b35391c41df993ad1b13d4e4e2a.스크린샷 2024-05-28 104551.png.png
  public/img/7f7327a70f1b42dea6f54776ad26f9a2.png
  public/img/8679682737c543f0b1fce91cba2cd172.png
  public/img/8aa59e81c245426ebc4fee51ab66cd1a.png
  public/img/a0ad0667d4dd47a6bd718a62f4d89b58.png
  public/img/approvals/26a39b4e638e410ead76ffde10aa804b.png
  public/img/b2a652ff29e1454d88df5fa34b4ba50b.png
  public/img/b5022d88de9f40d492903a7837c65d4e.png
  public/img/c0611e39170143588d1ecc0045fa3315.ico
  public/img/cbce1976f14a4852b0ba1807c73a8e3b.png
  public/img/eaaf4ae969e5423a835dbf31e29f0e16.png
  public/img/ec1707ace06e4d0d82a89d78950d6a42.png
  public/img/m1.png.ccdc67ec979549888b84fdfa04302366.png
  public/img/m1.png.png
  public/img/m2.png.68c2533b53d74aafa75b460a1bb29426.png
  public/img/m2.png.png
  public/img/m2.pngca6f7fe6520749fbb7444f228a668a9e.png
  public/img/m2.pngf645f0a3676346299c7e8f33e498c97c.png
  public/img/m3.png.c189d50f140c46bf896da33a9b27b68c.png
  public/img/m3.png.png
  public/img/m5.png9de7112aa23245c18c67b2705e680372.png
  public/img/pikachu.png.png
  public/img/스크린샷 2024-03-20 114151.pngfdd0477a2e784ccea69f9fe90593ae9a.png
  src/apis/MemberAPICalls.js
  src/components/form/DepartmentForm.js
  src/components/form/UpdatePWForm.js
  src/pages/Error.js
  src/pages/members/Departments.js
  src/pages/members/InsertMember.js
  src/pages/members/Member.js
  src/pages/members/MyPage.js
  src/pages/members/OrganizationChart.js
Labels: 기능구현, 디벨롭

#174 [Feature-0529](#5) - 전자결재목록 - 카테고리유지
  src/apis/ApprovalAPICalls.js
  src/components/approvals/AppCategory.js
  src/components/approvals/AppList.js
  src/components/commons/Sidebar.js
  src/pages/Main.js
  src/pages/approvals/ApprovalDetail.js
  src/pages/approvals/Approvals.js
  src/pages/approvals/InsertApproval.js
Labels: 디벨롭

#175 [Feature-0529] Mail/Resource - 받은 메일 발신자 부서 추가 / 주석 제거
  src/apis/MailAPICalls.js
  src/components/contents/Editor.js
  src/components/form/MailForm.js
  src/components/items/mails/MailContent.js
  src/components/items/mails/MailTable.js
  src/components/items/mails/ReplyMailContent.js
  src/components/lists/mails/ReceiveMail.js
  src/components/lists/mails/SendMail.js
  src/pages/mails/Mail.js
  src/pages/mails/MailDetail.js
Labels: 디벨롭

#176 [Feature-0529](#151) - comment - 댓글 수정
  public/img/1분기 성과보고서.hwp8dab61633a6a40ceacb84cca398140aa.hwp
  public/img/2분기 목표 및 일정.hwpe47864bf5de54b3e8f7133ed7b440e2b.hwp
  public/img/3c40e44b45934a7eba680d6173012ca6.실무에서 쓰이는 약어(코드리뷰).txt.txt
  public/img/402e6df4e26f4713ae87c68b022d26b0.m1.png.png
  public/img/4acce4d61c1e4c318768038f0087f7bf.png
  public/img/9352123b084c4ee699bca42c008eed4b.m5.png.png
  public/img/9fe36b77505c49bfa1d3166f00546e18.m3.png.png
  public/img/데이터 동기화 문제 해결 방안_2024.05.28.xlsx3db674ec731945c985921064b8341598.xlsx
  public/img/외부 컨설턴트 피드백 및 제안 사항_2024.05.28.xlsxdc726cb30bae422db6b4ca448b4938a6.xlsx
  public/img/프로젝트 진행상황보고서_2024.05.28.xlsx2cfea01149f1485490735f904d874da3.xlsx
  src/apis/CommentAPICalls.js
  src/components/commons/Sidebar.js
  src/components/form/InsertReserveForm.js
  src/components/form/UpdateCommentForm.js
  src/components/items/boards/Board.js
  src/components/items/comment/Comment.js
Labels: 기능구현

#177 [Feature-0529] (departmetns,positions) 권한별 차단
  public/images/DepIcon.png
  public/images/DepIcon2.png
  public/images/DepIcon3.png
  public/images/noAuth.gif
  public/img/3bfec856824945289006978b78005841.png
  src/apis/MemberAPICalls.js
  src/apis/ScheduleAPICalls.js
  src/pages/members/Departments.js
  src/pages/members/Member.js
  src/pages/members/OrganizationChart.js
  src/pages/members/Positions.js
  src/style.css
Labels: 디벨롭

#178 [Feature-0529](InsertMember)-사내메일자동완성
  public/images/ketchupAni.gif
  public/img/1544fa1efb7f4449814197d7e58b1818.png
  src/pages/Main.js
  src/pages/members/InsertMember.js
  src/pages/members/Members.js
  src/pages/members/OrganizationChart.js
Labels: 디벨롭

#179 [Feature-0529] Mail - 답장 수정
  src/components/form/ReplyMailForm.js
  src/components/items/mails/ReplyMailContent.js
  src/pages/resources/Resources.js
Labels: 디벨롭

#180 [Feature-0529](#170) - calendar - 일정 참여자별, 일정상태별 필터링 추가
  public/img/27a621221ab145dc8681212dd8269dde.png
  public/img/85acfca96988441e881907a5c6f0cad3.png
  public/img/a627cc0503fb48a585ce6aa6d367ada0.png
  public/img/dc0105ef55c14c62b81b23b15d7b5bf9.png
  src/components/form/ScheduleDetail.js
  src/components/form/ScheduleForm.js
  src/components/lists/subscriptions/SubscriptionList.js
  src/pages/schedules/calendar.js
Labels: 디벨롭

#181 [Feature-0530](OrganizationChart) - 조직도 수정
  package-lock.json
  package.json
  public/img/16e213b786fc41399c1da54f2b034611.gif
  public/img/310994ce573845daaa55ae8756da4e6e.png
  src/pages/members/OrganizationChart.js
Labels: 디벨롭

#182 [Feature-0530](#131) - calendar, reserve - 일정, 예약 유효성 검사 보강, UI,UX 개선
  src/apis/ScheduleAPICalls.js
  src/components/form/DeleteReserveForm.js
  src/components/form/InsertReserveForm.js
  src/components/form/ReserveDetail.js
  src/components/form/ScheduleDetail.js
  src/components/lists/subscriptions/SubscriptionList.js
  src/pages/reserves/Reserve.js
  src/pages/schedules/calendar.js
Labels: 기능구현, 디벨롭

#184 [Feature-0530] - {Api} AWS서버 연동
  src/apis/Api.js
  src/apis/MemberAPICalls.js
Labels: 디벨롭

#185 [Feature-0530](#182) - calendar, reserve - 일정, 자원예약 UI, UX 및 유효성 검사 수정
  package-lock.json
  package.json
  src/components/form/ReserveDetail.js
  src/components/lists/subscriptions/SubscriptionList.js
  src/pages/Main.js
  src/pages/reserves/Reserve.css
  src/pages/schedules/calendar.js
Labels: 디벨롭

#186 [Feature-0530] Mail - 수신자 ... 수정
  src/apis/MailAPICalls.js
  src/apis/ResourceAPICalls.js
  src/components/items/mails/MailTable.js
  src/pages/mails/mail.css
Labels: 디벨롭

#187 [Feature-0530] - css 수정
  src/apis/BoardAPICalls.js
  src/apis/NoticeAPICalls.js
  src/components/form/InsertBoardForm.js
  src/components/form/UpdateBoardForm.js
  src/components/form/UpdateNoticeForm.js
Labels: 디벨롭

#188 [Feature-0530](Api.js) - 주소변경
  src/apis/Api.js
  src/apis/MailAPICalls.js
  src/apis/MemberAPICalls.js
  src/components/form/InsertReserveForm.js
  src/components/form/ScheduleDetail.js
  src/components/form/ScheduleForm.js
  src/pages/resources/Resources.js
Labels: 디벨롭

#189 [Feature-0530] - api 수정
  src/apis/BoardAPICalls.js
  src/apis/NoticeAPICalls.js
  src/apis/ResourceAPICalls.js
Labels: 디벨롭
